/*
 */
package fitnessapp;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ListSelectionModel;

/**
 *
 * @author celine_yin
 */
public class MemberTrainingHistoryDialog extends javax.swing.JDialog {
    private HFGUI hfgui;
    private Member theMember;
    private TrainingHistTableModel thtm;   // to store data for the training history table
    
    /**
     * Creates new form MemberTrainingHistoryDialog
     */
    public MemberTrainingHistoryDialog(java.awt.Frame parent, boolean modal, Member theMember) {
        super(parent, modal);
        initComponents();
        setTitle("Member Training History");
        setSize(850, 550);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        // make HFGUI the parent of the dialog also
        hfgui = (HFGUI) this.getParent();

        this.theMember = theMember;
        trainingHistLbl.setText(theMember.getFullName() + "'s Training History");
        
        setupTableModels();          // call this method to set up table models
    }

    /**
     * A method to manage the table views and table models for member's training history
     */
    public void setupTableModels() {      
        if (theMember.getNumTrainings() == 0) {
            displayTrainingLbl.setText("No training history to show.");
        }

        thtm = new TrainingHistTableModel(theMember.getTrainingSessions());   // get all member registered sessions
        trainingHistTable.setModel(thtm);          // put the data in the Jtable
        
        ArrayList<TrainingSession> sortedSessions = theMember.getTrainingSessions();

         sortByCB.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                if (ie.getItem().equals("Session ID")) {
                    Collections.sort(sortedSessions);
                    thtm.setSessions(sortedSessions);
                    thtm.fireTableDataChanged();
                }
                else if (ie.getItem().equals("Date")) {
                    SessionDateComparator dateComparator = new SessionDateComparator();
                    Collections.sort(sortedSessions, dateComparator);
                    thtm.setSessions(sortedSessions);
                    thtm.fireTableDataChanged();
                } else {
                    ClassTypeComparator classTypeComparator = new ClassTypeComparator();
                    Collections.sort(sortedSessions, classTypeComparator);
                    thtm.setSessions(sortedSessions);
                    thtm.fireTableDataChanged();
                } 
            }
         });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainingHistLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trainingHistTable = new javax.swing.JTable();
        closeBtn = new javax.swing.JButton();
        displayTrainingLbl = new javax.swing.JLabel();
        sortByCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        trainingHistLbl.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        trainingHistLbl.setForeground(new java.awt.Color(153, 0, 102));
        trainingHistLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trainingHistLbl.setText("My Training History");

        trainingHistTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(trainingHistTable);

        closeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        closeBtn.setText("Close");
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        displayTrainingLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayTrainingLbl.setText(" ");

        sortByCB.setBackground(new java.awt.Color(153, 0, 102));
        sortByCB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sortByCB.setForeground(new java.awt.Color(255, 255, 255));
        sortByCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by", "Session ID", "Date", "Class Type" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trainingHistLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(sortByCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(displayTrainingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 811, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeBtn)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trainingHistLbl)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayTrainingLbl)
                    .addComponent(sortByCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(closeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberTrainingHistoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberTrainingHistoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberTrainingHistoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberTrainingHistoryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MemberTrainingHistoryDialog dialog = new MemberTrainingHistoryDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel displayTrainingLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sortByCB;
    private javax.swing.JLabel trainingHistLbl;
    private javax.swing.JTable trainingHistTable;
    // End of variables declaration//GEN-END:variables
}
