/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Week8N9N10N11GUI;

import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author celine_yin
 */
public class OrderListWindow extends javax.swing.JDialog {

    private Restaurant theRestaurant;       // the restaurant
    private MenuItem theMenuItem;           // the current menu item being ordered
    private Order theOrder;                         
    private DefaultListModel listModel;       // the current order
    /**
     * Creates new form OrderListWindow
     */
    public OrderListWindow(java.awt.Frame parent, boolean modal, Order theOrder) {
        super(parent, modal);
        this.theRestaurant = ((RestaurantGUI) parent).getRestaurant();
        this.theOrder = theOrder;
        initComponents();
        tableNoLabel.setText("Table No " + theOrder.getTable().getTableNo());
        orderNoLabel.setText("Order No " + theOrder.getOrderNo());
        listModel = new DefaultListModel();
        orderList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableNoLabel = new javax.swing.JLabel();
        orderNoLabel = new javax.swing.JLabel();
        itemNoLabel = new javax.swing.JLabel();
        itemNoTF = new javax.swing.JTextField();
        menuItemLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qtyCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        requestTF = new javax.swing.JTextField();
        addItemBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList();
        cancelBtn = new javax.swing.JButton();
        confirmBtn = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableNoLabel.setText("Table No:");

        orderNoLabel.setText("Order No:");

        itemNoLabel.setText("Item No");

        itemNoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemNoTFFocusLost(evt);
            }
        });

        menuItemLabel.setText("menu Item Description");

        jLabel1.setText("Quantity");

        qtyCombo.setEditable(true);
        qtyCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        qtyCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyComboActionPerformed(evt);
            }
        });

        jLabel2.setText("Special Request");

        addItemBtn.setText("Add Item");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Ordered Items:");

        orderList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(orderList);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        confirmBtn.setText("Confirm Order");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        totalLabel.setText("Order Total: $0.00");

        deleteButton.setText("Delete Selected Items");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(cancelBtn)
                .addGap(113, 113, 113)
                .addComponent(confirmBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tableNoLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemNoLabel)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(requestTF, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                        .addComponent(addItemBtn))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(orderNoLabel)
                                            .addGap(61, 61, 61))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(qtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(297, 297, 297)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(itemNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(menuItemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableNoLabel)
                    .addComponent(orderNoLabel))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemNoLabel)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuItemLabel))
                        .addGap(28, 28, 28)
                        .addComponent(qtyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(requestTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemBtn))
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(totalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelBtn)
                            .addComponent(confirmBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qtyComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyComboActionPerformed

    private void itemNoTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemNoTFFocusLost
        // TODO add your handling code here:
        String itemStr = itemNoTF.getText();
        if (!itemStr.equals("")){
            int itemNo = Integer.parseInt(itemStr);
            theMenuItem = theRestaurant.findMenuItem(itemNo);
            if (theMenuItem != null){
                menuItemLabel.setText(theMenuItem.getDescription());
                menuItemLabel.setForeground(Color.black);
            }
            else {
                menuItemLabel.setText("Menu Item not found!");
                menuItemLabel.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_itemNoTFFocusLost

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        // TODO add your handling code here:
        int qty = Integer.parseInt((String) qtyCombo.getSelectedItem());
        String req = requestTF.getText();
        OrderItem oi = theOrder.addOrderItem(theMenuItem, qty, req);
        if (oi == null)             // item exists in order
            JOptionPane.showMessageDialog(this, "Item already ordered. Delete to change", "Error", JOptionPane.ERROR_MESSAGE);
        else {
            listModel.addElement(oi);
            theMenuItem = null;         // reset the order item input field
            itemNoTF.setText("");
            qtyCombo.setSelectedIndex(0);
            requestTF.setText("");
            updateOrderTotal();
        }
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        List<OrderItem> unwanted = orderList.getSelectedValuesList();
        for (OrderItem ui:unwanted){
            theOrder.removeItem(ui);        // delete from order
            listModel.removeElement(ui);    // remove from view
        }
        updateOrderTotal();             // call the method to update label
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(this, "Confirm cancel order#" + theOrder.getOrderNo() + "?", 
                "Cancel Order", JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION){
            theOrder.setStatus("Cancelled");
            this.dispose();
        }
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        theOrder.setStatus("Confirmed");
        JOptionPane.showMessageDialog(this, "Order Number: " + theOrder.getOrderNo() + " is confirmed");
        this.dispose();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void updateOrderTotal() {
        double totalPrice = theOrder.getTotal();
        String result = String.format("Order Total: $%.2f", totalPrice);
        totalLabel.setText(result);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderListWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderListWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderListWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderListWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OrderListWindow dialog = new OrderListWindow(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel itemNoLabel;
    private javax.swing.JTextField itemNoTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menuItemLabel;
    private javax.swing.JList orderList;
    private javax.swing.JLabel orderNoLabel;
    private javax.swing.JComboBox<String> qtyCombo;
    private javax.swing.JTextField requestTF;
    private javax.swing.JLabel tableNoLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
