/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Week8N9N10N11GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author celine_yin
 */
public class RestaurantGUI extends javax.swing.JFrame {
    private Restaurant rest;        // instance variable for the GUI
    /**
     * Creates new form RestaurantGUI
     */
    public RestaurantGUI() {
        initComponents();
        rest = new Restaurant();    // create the object
    }
    
    // Getter for Restaurant
    public Restaurant getRestaurant() {
        return rest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuItemButton = new javax.swing.JButton();
        newOrderButton = new javax.swing.JButton();
        viewOrderBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newFileOption = new javax.swing.JMenuItem();
        loadFileOption = new javax.swing.JMenuItem();
        saveFileOption = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemOption = new javax.swing.JMenuItem();
        viewOrdersOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Restaurant Ordering System");

        menuItemButton.setText("Maintain Menu Item");
        menuItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemButtonActionPerformed(evt);
            }
        });

        newOrderButton.setText("Create New Order");
        newOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newOrderButtonActionPerformed(evt);
            }
        });

        viewOrderBtn.setText("View All Orders");
        viewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        newFileOption.setText("New");
        newFileOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileOptionActionPerformed(evt);
            }
        });
        jMenu1.add(newFileOption);

        loadFileOption.setText("Load");
        loadFileOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileOptionActionPerformed(evt);
            }
        });
        jMenu1.add(loadFileOption);

        saveFileOption.setText("Save");
        saveFileOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileOptionActionPerformed(evt);
            }
        });
        jMenu1.add(saveFileOption);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuItemOption.setText("Manage Menu Items");
        menuItemOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOptionActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemOption);

        viewOrdersOption.setText("View Orders");
        viewOrdersOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersOptionActionPerformed(evt);
            }
        });
        jMenu2.add(viewOrdersOption);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(newOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(menuItemButton)
                .addGap(38, 38, 38)
                .addComponent(newOrderButton)
                .addGap(41, 41, 41)
                .addComponent(viewOrderBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemButtonActionPerformed
        // TODO add your handling code here:
        MenuItemDialog miDialog = new MenuItemDialog(this, true);
        miDialog.setVisible(true);

    }//GEN-LAST:event_menuItemButtonActionPerformed

    private void newOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newOrderButtonActionPerformed
        // TODO add your handling code here:
        NewOrderDialog orderDialog = new NewOrderDialog(this, true);
        orderDialog.setVisible(true);
    }//GEN-LAST:event_newOrderButtonActionPerformed

    private void viewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderBtnActionPerformed
        // TODO add your handling code here:
        OrderStatusWindow osw = new OrderStatusWindow(rest, this);
        osw.setVisible(true);
    }//GEN-LAST:event_viewOrderBtnActionPerformed

    private void menuItemOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOptionActionPerformed
        // TODO add your handling code here:
        menuItemButtonActionPerformed(evt);             // call the method
    }//GEN-LAST:event_menuItemOptionActionPerformed

    private void viewOrdersOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersOptionActionPerformed
        // TODO add your handling code here:
        viewOrderBtnActionPerformed(evt);
    }//GEN-LAST:event_viewOrdersOptionActionPerformed

    private void saveFileOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileOptionActionPerformed
        // TODO add your handling code here:
        // call the static method in FileHandling class,
        // pass this JFrame and the
        // Restaurant object to save
        FileHandling.saveToFile(this, rest);
    }//GEN-LAST:event_saveFileOptionActionPerformed

    // User chooses to create new restaurant
    private void newFileOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileOptionActionPerformed
        // TODO add your handling code here:
        if (rest != null) {
            int n = JOptionPane.showConfirmDialog(this, "Would you like to save your changes first", "Warning", JOptionPane.YES_NO_CANCEL_OPTION);
            if (n == JOptionPane.YES_OPTION)
                FileHandling.saveToFile(this, rest);
        }
        rest = new Restaurant();
        rest.updateSequences();
    }//GEN-LAST:event_newFileOptionActionPerformed

    // load Restaurant object from file
    private void loadFileOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileOptionActionPerformed
        // TODO add your handling code here:
        if (rest != null)               // there's an existing Restaurant object
        {
            int n = JOptionPane.showConfirmDialog(this, 
                    "Would you like to save your changes first", 
                    "Warning", JOptionPane.YES_NO_CANCEL_OPTION);
            if (n == JOptionPane.YES_OPTION)
                FileHandling.saveToFile(this, rest);
        }
        rest = (Restaurant) FileHandling.readFromFile(this);            // downcast
        rest.updateSequences();
    }//GEN-LAST:event_loadFileOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem loadFileOption;
    private javax.swing.JButton menuItemButton;
    private javax.swing.JMenuItem menuItemOption;
    private javax.swing.JMenuItem newFileOption;
    private javax.swing.JButton newOrderButton;
    private javax.swing.JMenuItem saveFileOption;
    private javax.swing.JButton viewOrderBtn;
    private javax.swing.JMenuItem viewOrdersOption;
    // End of variables declaration//GEN-END:variables
}
