package fitnessapp;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * A JFrame to display Member menu options
 * @author B1601563
 */
public class MemberMenuFrame extends javax.swing.JFrame {
    private HFGUI hfgui;
    private Member theMember;
    
    /**
     * Creates new form MemberMenuFrame
     */
    /**
     * Constructor for MemberMenuFrame
     * @param theParent JFrame HFGUI
     * @param theMember the logged in member user
     */
    public MemberMenuFrame(HFGUI theParent, Member theMember) {
        super();
        initComponents();
        setTitle("Member Menu");
        setSize(620, 400);
        // set location to center of screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        // make HFGUI the parent of this Frame
        hfgui = theParent;

        // make HFGUI not visible
        hfgui.setVisible(false);
        
        this.theMember = theMember;
        
        // Display personalized welcome message for member
        welcomeMsgLbl.setText("Welcome, " + theMember.getFullName());
        
        // Do not allow user to close the application unless they log out
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeMsgLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editProfileBtn = new javax.swing.JButton();
        viewTrainingBtn = new javax.swing.JButton();
        viewAllSessionsBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeMsgLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        welcomeMsgLbl.setForeground(new java.awt.Color(153, 0, 102));
        welcomeMsgLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        welcomeMsgLbl.setText("Welcome, member.");
        welcomeMsgLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("What would you like to do?");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        editProfileBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        editProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessapp/editProfileIcon.png"))); // NOI18N
        editProfileBtn.setText(" Edit Profile");
        editProfileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBtnActionPerformed(evt);
            }
        });

        viewTrainingBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        viewTrainingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessapp/trainHistIcon.png"))); // NOI18N
        viewTrainingBtn.setText(" View Training History");
        viewTrainingBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTrainingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTrainingBtnActionPerformed(evt);
            }
        });

        viewAllSessionsBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        viewAllSessionsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessapp/sessionsIcon.png"))); // NOI18N
        viewAllSessionsBtn.setText(" Register For Session");
        viewAllSessionsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAllSessionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllSessionsBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(255, 51, 51));
        logOutBtn.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        logOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessapp/logoutIcon.png"))); // NOI18N
        logOutBtn.setText(" Log Out");
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(welcomeMsgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewAllSessionsBtn)
                                    .addComponent(viewTrainingBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editProfileBtn)
                                    .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeMsgLbl)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewAllSessionsBtn)
                    .addComponent(editProfileBtn))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewTrainingBtn)
                    .addComponent(logOutBtn))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * A method to allow theMember to edit profile details when editProfileBtn is clicked
     * @param evt 
     */
    private void editProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBtnActionPerformed
        EditMemberProfileDialog empDialog = new EditMemberProfileDialog(hfgui, true, theMember);
        empDialog.setVisible(true);
    }//GEN-LAST:event_editProfileBtnActionPerformed

    /**
     * A method to allow theMember to view training history when viewTrainingBtn is clicked
     * @param evt 
     */
    private void viewTrainingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTrainingBtnActionPerformed
        MemberTrainingHistoryDialog mthDialog = new MemberTrainingHistoryDialog(hfgui, true, theMember);
        mthDialog.setVisible(true);
    }//GEN-LAST:event_viewTrainingBtnActionPerformed

    /**
     * A method to allow theMember to view all available sessions to register when viewAllSessionsBtn is clicked
     * @param evt 
     */
    private void viewAllSessionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllSessionsBtnActionPerformed
        UpcomingSessionsWindow usWindow = new UpcomingSessionsWindow(hfgui, true, theMember);
        usWindow.setVisible(true);
    }//GEN-LAST:event_viewAllSessionsBtnActionPerformed

    /**
     * A method to allow theMember to log out when logOutBtn is clicked
     * @param evt 
     */
    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        this.dispose();
        hfgui.setVisible(true);
        hfgui.setEnabled(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberMenuFrame(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editProfileBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton viewAllSessionsBtn;
    private javax.swing.JButton viewTrainingBtn;
    private javax.swing.JLabel welcomeMsgLbl;
    // End of variables declaration//GEN-END:variables
}
